---
title:  'How to fill a water balloon with paint and then paint with it'
---
<p style="text-align:right">June 2021</p>
<p style="text-align:right">[Katherine Lee](https://katelee168.github.io/),  [misc ↩](https://katelee168.github.io/misc)</p>

<video controls="controls" width="650" height="486" name="boop">
  <source src="images/paint.mov">
</video>


1. Tell your friend you want to throw paint at the wall with your bare hands.
2. Appreciate that your friend suggests living out your Princess Diaries dreams and throw darts at water balloons full of paint. 
3. Run around Boston collecting paint, water balloons, squirt guns, and bubbly water.
    a. Visit Sam's house four times because you forgot the super glue, the garden hose, and the avocados! Pet her cats.
4. Return home and make guac because it is now 1pm and you all had cold pizza for breakfast.
5. Use your friend's old bedsheets as a canvas and as a drop cloth because she just bought a new house (yay!), and you agreed to try to get rid of them.
6. Fill the water balloons with paint.
    a. One of you bruises your cheeks trying to blow up those damn balloons. One of you inhales paint. 
    b. Proceduralize blowing up the balloons.
        1. Remove the water balloon from the straw.
        2. Put the water balloon back on the straw without the rubber band.
        3. Blow while stretching out the balloon with your left hand. Hold the balloon tight on the straw with your right. Blow the balloon about 1/4 of the way.
        4. Grasp the balloon with your left hand, leaving a little bit of space between your fingers and the end. Make a seal with the water balloon and the paint bottle.
        5. Invert the paint bottle. Squeeze!
        6. Turn the paint bottle right side up. Wait for the paint to drain back into the balloon and into the paint bottle so you don't end up with paint spit-up.
        7. You're still holding the water balloon with your left hand on the paint bottle, so use your right to milk that paint down into the balloon.
        8. Place your fingers a little way down your balloon, stick the straw back into the water balloon, seal it with your other fingers.
        9. Stretch and blow the balloon.
        10. Try not to pop it while tying.
7. Realize it's now 4pm and you should do some test runs. Also maybe you should do the real run. 
8. Tape the balloons up.
9. Feed the dog. 
9. Throw darts at the wall.
10. Throw rocks at the wall.
11. Attempt to explain the procedure to the new arrival. He gets lost somewhere around step 5. Paint everywhere. 
12. Mix paints together in the balloon. The Procedure is complicated.
13. Have bad aim, have better aim, roll around in paint.

## Observations:

* Act fast, the paint can dry in the balloon.
* More paint != cooler splatter
* Roll the paint around in the balloon -> cooler splatter
* More air = sometimes the darts bounce off the balloon??? 
