---
title: The Rationalist Community circa 2016-2018 and its growth
---
<p style="text-align:right">August 2021</p>

I was first exposed to the rationalist and effective altruist communities at Princeton in 2016. Moving to the bay area to work in AI research, I mingled with many folks in the scene. I wouldn't call myself a member of the community, but my continual encounters have forced me to question why I find the community both so enticing and why I hold back so much from full immersion. Here's a collection of thoughts.

As a note, I'm given to understand that the rationalist scenes in different cities are quite different (Berlin, Oxford, Cambridge (Mass), SF, etc.) so I should stress that this is only my experience with a particular branch of the SF scene. 

## Perfectionism
I, too, felt responsible. Since I both suffered from perfectionism and an overinflated sense of self-importance, I felt responsible for problems larger than I could control. 
<!-- I, too, felt responsible for parts of the world I thought I could control. I thought, in my perfectionist way, that I had to do the best job ever in dealing with it.  -->
The community seemed to feel responsible for figuring out the best solution for the world's problems. Doing a net-positive thing, somehow didn't feel good enough. It had to solve the global optimization problem.

My perfectionist tendencies loved global optimization problems. I factored everyone in my life into my grand schemes, giving my friends complicated schedules planned down to the fifteen minute mark of where we would be and who we would be meeting up with. I planned no slack. If we got off schedule, we were behind.

Most times, it worked out. I could cram an impossible number of hangouts, games, and chores in a day. When it didn't work out, I melted into a puddle of anxiety and stress. If someone else was late, or god forbid the train was late, I frantically rescheduled everything else that day. 

I've been told my capacity for dealing with logistics is a great strength. I'm here to say that I've completely burned it out. Today, the thought of planning for anything is terrifying. If I have to transport my body between cities, I can get literally nothing else done that day. 

So I don't think always trying to solve the global optimization problem is a good thing. Even if you think you know what the solution is, it doesn't fall to your shoulders to implement it. People have different strengths, and we can contribute to different capacities. Do something you enjoy doing that makes the neighborhood around you a little better. Everyone experiences and sees different things, you can be open to helping in ways that you enjoy and are good at, but just because you could do something, doesn't mean you have to. 

This certainly ties into the tech scene's focus on scale. Solving a problem for just the few people around you is not enough. You must at least have a plan for bringing it across the country if not to the whole world. 

### A failure mode: 
I have a friend who decided several years ago that he loved another individual's research and that helping to advance it was the most impactful work he could do. This friend signed up for a job working with the researcher doing all the grunge infrastructure work. He hated it. Surely some people love setting up machines to run complicated models in parallel, but he was not one of them. He still felt that he wanted to contribute, and furthering this research felt like the most important thing he could be doing. He couldn't shake the feeling that he was incompetent and useless. I'm sure he wasn't. His body was just revolting when his mind wouldn't let them go.

My friend was medicated and self medicating, and I wished he could just close their eyes for a moment and let himself do something that made just him happy. 
<!-- Then, maybe they could find a thing that made him happy and did a small good in the world.  -->
It felt like he wasn't allowed to put himself first.

To be honest, I wish I could do that too. But, easier said than done, it's hard to say what brings me joy! And I find so many causes meaningful! There are many possible lives one could live. 

## Collective action

All that said, I've always respected how effectively the rationalist community could rally behind a cause. Since people bought the idea that they should do the most effective thing, all it took was determining a "thing."

I'm simplifying, of course, but the number of people who are directly employed by organizations created by other rationalists is impressive to me. 

This might also be true with other movements as well, and perhaps with political campaigns. I just happen to have the front row seats to this one. 

The frequent discussions about long-term AI risk in the rationalist community ran absolutely counter to my work place where up until very recently, even short-term AI risk (like perpetuating harmful stereotypes in decision making systems and violating privacy expectations of data used for training) was not widely discussed. 


## It feels traumatizing.

Being told that you can and must do the most good for the world is exhausting and completely wrong. The world is made up of systems, and systems are made of individuals who have influence on the system but are not the system. Thinking in systems is certainly a framework within the community and they would completely agree that finding the leverage points in the system and taking collective action is important. 
<!-- The amount of responsibility individuals feel along with the emphasis on collective action, and playing the part that you are best suited for^[As opposed to the part that suits you best.], feels like an exhausting tension. -->

The community has a tendency to escalate the scale of thinking and responsibility, zooming out further and further from your small community. Your perceived responsibility grows in kind. For the people who are driven to the rationalist community through some form of perfectionist thinking, this can fan the fan the flames and the responsibility and corresponding anxiety can become all-consuming. 

<!-- Some form of perfectionist thinking drives people to the rationalist community. The community can escalate the scale of thinking and move people towards existential risk (or x-risk) questions. Your preceived responsibility towards the world grows and grows, -->


## Growth
<!-- It's been cool to watch the rationalist community change so much over the past few years.  -->
The community I'm writing about already feels like a thing of the past. I doubt that anything I've written here is shocking to anyone who's been around the community for some time. Things take time, but I'm stunned by how much the community has become aware and addressed some of what I've written here.

In 2018, someone from OpenPhil reached out to learn about my qualms about the EA/Rationalist community^[Someone had apparently reported me! (I didn't actually mind.)]. As impressed as I was at the time that they were taking steps to confront criticisms they had been hearing, I was skeptical that anything would change. 

I'm not sure what's harder, changing as an individual or as a community. The tech scene has certainly had a moment of reckoning, and when I look back on the last four years, it feels like so much has changed. In 2017, the fairness in machine learning conversation was just getting started, and we didn't yet have good ways of talking about it. Today, the conversation is mainstream (and sometimes appropriated), appearing in news outlets and company press releases. 

## Meditation
There's always been a focus on meditation and spirituality in the tech community and this bleeds in with the rationalist communities. 
There's a trope of the startup CEO using meditation to extract more productivity from themselves. 
In this case, it felt like meditation was being used to suppress the self. 
But to ignore the emotional responses completely, and not work through them in conjunction with finding a calmer state of mind, seems misguided. 

Since moving out of the bay area, I've kept in touch with just a handful of people, and I've been shocked to see an increased focus on individual experience and exploring emotions. 
I once had an argument with someone over the notion that there was a most interesting thing about a person. 
Regardless of if there is, I felt like I surely wouldn't have passed this person's test, and at the time, that made me feel unvalued. 
In trying to communicate that to this friend-of-a-friend, the feelings I shared seemed to continually be discounted as "but it doesn't make sense."
Today this person writes publicly about exploring their full emotional space. 
So not quite moving to empathy, but a dramatic increases in importance of emotions in their life.

Change happens both when people invest in the system, and when people vocalize their hurt, possibly without 
    This is also a form of investment, believing that the system can change with more information even if they aren't the one to execute on it.

<!-- I was deeply skeptical about the focus on rationality within the rationality community. I too, wanted to think about the global optimization problem. -->

The perfectionism rampant among people 










https://twitter.com/tamigraph/status/1432124280859357189

So much of academic labor exploitation thrives on a culture of "If I don't do this task, no one else will and others will suffer as a result" to the point where people feel obligated to keep working when they are officially off the clock or even after their jobs have ended

<p style="text-align:right">[Katherine Lee](https://katelee168.github.io/),  [misc ↩](https://katelee168.github.io/misc)</p>
