---
title: "Creating Safety"
---

On days when I feel confident, I feel like I can handle whatever comes my way. I feel secure in myself and my ability to adapt. On days when I don't feel as confident, I don't feel safe, and I think about money. 

Money offers protection. If your car breaks down, being able to rent another car and pay to fix it can buy some peace of mind. If you become injured, having money enough to cover medical expenses, and take time off work to recover means that when you do go back, you can be present.
It makes me incredibly sad to think that not everyone can afford to pay medical bills, or take time off of work to fully recover. When my parents had just moved to the US so that my dad could go to grad school, my mom's waitressing job paid most of the bills. When she had me, my mom went back to work before I was one month old, after a painful, long labor and an emergency c-section. 
<!-- She was afraid her hospital visit would be too expensive, so she asked to be discharged early against her doctor's orders.  -->

While my mom faced so many difficult challenges, I think she's most defined by her constant alertness.
She's go, go, go--every minute is precious.
<!-- She says every word three times -->
On the drive to the grocery store, she maps out her route in the store. "Otherwise you would waste time!"" She tells me as we turn into the parking lot. 

What money really buys you is time. Time enough to press pause on a difficult situation. Time to grieve. Time freed to spend in literally any other way. 

So when I'm stressed, I'm looking for someone to tell me that I don't have to make that deadline, that growth and learning are long-term goals, and that I don't have to be anywhere or be anyone right this moment. And of course, I want to know that I'm going to be okay. 

People find safety in different ways--family, support networks, the government, mentors, etc. If you have your wits about you, then you can handle and survive challenges. If, for whatever reason, your wits are taking a break, it becomes a heck of a lot harder to deal with the little things that keep cropping up. It helps a lot to have a support network. I recently heard the word "hyper-independence" and that made me think of both my mom and me. The word "hyper" at the beginning there makes me feel like this isn't something to aspire to. 


<p style="text-align:right">July 6, 2021</p>
<p style="text-align:right">[Katherine Lee](https://katelee168.github.io/),  [misc ↩](https://katelee168.github.io/misc)</p>
