---
title: "Creating Safety"
---

On days when I feel confident, I trust myself to adapt to however the day goes. On days when I don't feel as confident, I don't feel safe, and I think about money.

Money gives you runway to make mistakes. It means that an artist can blow through tubes and tubes of oil paint practicing and refining before finding a riff on the idea that they like. 

Money offers protection. If you become injured, having money enough to cover medical expenses, and take time off work to recover means that when you do go back, you can be present. When my parents had just moved to the US, my mom's waitressing job paid most of the bills. When she had me, my mom went back to work before I was one month old, after a painful, long labor and an emergency c-section. She couldn't afford to not be working. 

While my mom faced so many difficult challenges, I think she's most defined by her constant alertness.
She's go, go, go--every minute is precious.
On the drive to the grocery store, she maps out her route in the store. 
"Okay, you run in and grab the bread, because that's further away from everything else, then I'll go get the vegetables, and we'll meet up by milk and walk through snacks together."
"Otherwise you would waste time!"" She exclaims me as we turn into the parking lot. 

There's a Chinese proverb "一寸光阴一寸金，寸金难买寸光阴" which means, gold can't buy you time. But gold lets you buy someone else's time.

When I'm stressed, I want to be reminded that I have time to make mistakes. I don't have to make that deadline. I don't have to be anywhere or be anyone right this moment. I don't have to be go-go-go. 

You can find that safety in ways outside money. 
If you have extra capacity in your life, then you can take on new challenges. If you have your wits about you, then you can adapt and innovate. 
If you're already stretched thin, or if your wits are taking a break, it's helpful to have a support network: your family, community, or government. 

I recently heard the word "hyper-independence" and that made me think of both my mom and me. 
Hyper-independence is independence taken too far towards an inability to trust others or other systems. 
It can be a protective response from being let down in the past.  
Over the past many years, I've been learning and re-learning how to let other people participate in my life. 
<!-- A few months ago, I found myself crying in the living room of a house I was staying in short-term. Someone walked by and within five minutes had resolved the stressers on my day, and 
For years, I've felt that I was both responsible for dealing with all the things that  -->

There's obviously been a lot of discussion about universal basic income, and welfare, and I barely know anything about it. But I can tell you how it makes me feel to know that someone else, my community, my country has my back and there is only so far I can fall. Runway, protection, and time give you the opportunity to take risks and innovate. In our world, money buys you all those things, but we should add additional paths towards safety outside of independent accumulation of wealth.

<p style="text-align:right">July 6, 2021</p>
<p style="text-align:right">[Katherine Lee](https://katelee168.github.io/),  [misc ↩](https://katelee168.github.io/misc)</p>
