---
title:  'Slow down'

---


I don't mind that he did not live. In those moments when the whole house shook with your voice, I wanted to hide under my covers and bury myself deep within the embrace of a younger sister, a younger brother, but never an older brother. And I had always seen him as an older brother. 

When I graduated high school and walked down the blue halls, riding high on the waves of my classmates, you looked me in the eye and cried. He would have graduated from college this year. I learned he was four years older than me. <!-- I never knew he was four years older than me.  -->

In that moment, he felt too close.

I came home from the fancy, liberal arts college that Chinese immigrant families try to send their children to, forgetting that the liberal arts were meant to train students to pursue knowledge and speak up and not: put your head down and work, don't cause trouble. You said those words again, "As a woman, we can't." I could feel my own voice well up in my throat. Sometimes I don't care enough to be a woman, and I let it out, and I hear my screams. I squint my left eye as an apology to you, and you never hear me say sorry. 

You began starting your sentences with, "I know you don't like to hear about boys and girls, but..." <!-- and I wasn't sure what to say after that because I suppose that you had heard me. --> <!-- Revise this section -->
and I didn't know how to respond to that because, I guess, you already knew that I didn't like to hear it. 

"...girls shouldn't speak so fast." You told me once you used to speak quickly too, and when someone told you to speak more slowly, you told them that your brain moved too fast to speak so slowly. 

<!-- In that moment, you felt so close. -->
I admired you.

When I go to pro-choice rallies and I tell you, you say you understand. You've been there before, and you made a choice.

But that I must understand it was so hard. Some days you wake up, and you can feel him next to you. He never says anything, because you never taught him to speak. You reach out to touch him, but you never make it. I take your hand, but I never try to touch him. 

You cried when the doctor told you I was a girl.

When I sat in the doctor's office curled up in pain, you looked me in the eyes and told me, your daughter, that I couldn't take the birth control pills because it would mean, "You'll be more promiscuous," though you were the one who called me in sick from school when I couldn't move from pain. I couldn't understand, because taking those pills would help me avoid being in your situation, avoid losing someone's older brother.

You came to visit me, and someone made a penis joke in Chinese. You laughed. I turned to look at you because I didn't know what yángjù meant. You looked at me and said it was a boy's special part and told me I had the Chinese of a third grader. You hadn't taught me to speak. And now that I think about it, I couldn't even tell you what my special part is called. <!-- My vagina. -->

I called my boyfriend crying one night. It had been months since I had called in sick from work, and I stood, with my pants pulled down to my knees, the bulbous belly pulled my skin tight. I slapped my hand against it. It wasn't real. He told me, give it a day, maybe it would go away. But babies don't just go away. I ran through a pack of tests that night, all negative. But negative is never as sure as positive.

I learned you started showing thirteen weeks in.

<!-- 
There was no question about my choice.
* i dont know what to write about, maybe we should talk about
 -->
I named him Justin. Justin had come and gone. I'm not sure what you called him, if he had a name, if he was a him.

I wanted to call you to cry, but we've never talked about this, about sex. As a mother, I thought you might already know, and I was afraid of delivering the truth.

I don't think you've ever told him, my father. You are scared of driving, but you went yourself, cracking through freshly fallen snow. I knew you were thinking about how much you would not earn, but you told yourself this was right. You calculated the money left. Would there be enough to make rent this month? Would you have to ask your parents for help? But they could only send you yuan, and money wasn't meant to come from that side of the ocean.

When the nurse left your side, you stayed there, tears soaked your thick black hair. You wondered if having the child would have been better than not. Better than the guilt that settled into your bones. You had to be back for your shift. You drove yourself through the slushy roads. You never told him, my father.

Mom, you raised me to think I was special. That the world you inhabited would not be my home. I was to go out and create my own world. In my world, it would be like I told you when I was little. You had put your hand over your mouth and leaned towards the young, pregnant girl in the super market. I picked my head up to look at you and told you that it wasn't her fault. Because when two people love each other enough, a baby arrives.

I wanted to believe that I and my whomever were different from you and dad, that we would be prepared. We would be in love.

You looked me in the eyes and told me you didn't want me either. That you cried and weren't sure how you could afford me. But today, looking back, you have me, you have stability, and you couldn't imagine being here without me. Didn't we make it here together? 

It made you wonder about him. If you would have loved him like you loved me. 

Wrapped up in blankets and trying to push out the dark cold, we left early that morning. The two of us clenching our hands together. My boyfriend drove us. Would I love him as you loved me? 

We sat together in the waiting room, but I walked alone from there. I understood now why you cried when the doctor told you I was a girl.

You don't love my brother as you loved me, but he was wanted. He was the only one of us who had been pined for. Yet he's responsible for your hair littering the floor and the lines on your face that I buy you creams for.

Sometimes I wonder what life would be like with Justin. No longer the older sister, now the baby. So much of my person is made of speaking fast when you told me to slow down. Things are different with my brother. He's told to speak faster. I don't know how much of it is because I spoke fast and you wanted him to be more like me or how much is because of his yángjù. I don't mind that you told me to slow down.

The doctor knocked on the door, and I answered. 

I still don't mind that he didn't live.
<!-- Alt ending: And I still didn't mind that he didn't live, but I think that's more about me, than about you and him. -->

<p style="text-align:right">May 5, 2018</p>
<p style="text-align:right">[Katherine Lee](https://katelee168.github.io/),  [misc ↩](https://katelee168.github.io/misc)</p>