# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Katherine Lee
# email: youremailaddress@gmail.com
description: Katherine's description
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://katelee168.github.io" # the base hostname & protocol for your site

# Social settings
# 500px_url: 
# facebook_url: https://facebook.com
github_url: https://github.com/u/katelee168
# googleplus_url: https://plus.google.com/u/0/+katelee168
# instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/katherinelee8
# pinterest_url: 
# slack_url: 
# twitter_url: https://twitter.com/katelee168

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
# twitter:
  # username: katelee168
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 