--- 
author: 
  name: "Katherine Lee"
title: "Katherine Lee"
baseurl: ""
permalink: "/blog/:title"
description: "A [blank] and [blank]\n"
url: "http://katelee168.github.io"

markdown: kramdown
commentsystem: google
theme: minima

exclude: 
  - Gemfile
  - Gemfile.lock
gems: 
  - jekyll-feed

# Social
github_username: katelee168
linkedin_username: katherinelee8