---
title:  'Katherine Lee'
---
<!-- <p align="left"><sup>(she/her)</sup></p>
<div><img style="padding: 25px" src="images/me.jpeg" width="200" border="50" align="right"/></div>
<div style="text-align: justify">Hello!  -->

<img class="avatar" alt="Katherine Lee" src="./images/katherine-300x300.jpg">


I am a researcher at OpenAI and run the [GenLaw Center](https://genlaw.org). I study security and privacy in generative AI models and the legal implications those have.
Specifically, I evaluate data extraction (memorization) in generative AI models and attacks (mis-aligning) for generative AI models. 

Broadly, I'm interested in building machine learning systems we can reliably use. This means figuring out when models are brittle and creating or discovering knobs to change their behavior.

Previously, I worked at GDM (2023-2025) and Google Brain (2017-2023). You can find me on the internet: [Google Scholar](https://scholar.google.com/citations?user=bjdB4K8AAAAJ&hl=en), [Bluesky](https://bsky.app/profile/katherinelee.bsky.social), and [Goodreads](https://www.goodreads.com/user/show/44386744-katherine), or email me at [my github handle] @ gmail.com

If you need a bio for a talk, please use this one:

> Katherine is a researcher at OpenAI. Her work has provided essential empirical evidence and measurement for grounding discussions around concerns that language models infringe copyright, and about how language models can respect an individuals’ right to privacy and control of their data. Additionally, she has developed large language models (T5), developed methods of reducing memorization, and studied the impact of data curation on model development. Her work has been highly awarded at venues like: NeurIPS, ICML, ICLR, and USENIX.

## Selected Publications

Full list on [Google Scholar](https://scholar.google.com/citations?user=bjdB4K8AAAAJ&hl=en)

T5: Exploring the Limits of Transfer Learning with a Unified Text-to-Text Transformer [[JMLR](https://www.jmlr.org/papers/volume21/20-074/20-074.pdf)]<br/>
: [Colin Raffel](https://colinraffel.com/)\*, Noam Shazeer\*, Adam Roberts\*, **Katherine Lee**\*, Sharan Narang, Michael Matena, Yanqi Zhou, Wei Li, Peter J. Liu. June, 2020

Extracting Training Data from Large Language Models [[arxiv](https://arxiv.org/abs/2012.07805)] [[USENIX Oral](https://www.usenix.org/conference/usenixsecurity21/presentation/carlini-extracting)][[blog](https://bair.berkeley.edu/blog/2020/12/20/lmmem/)] [[video](https://www.usenix.org/conference/usenixsecurity21/presentation/carlini-extracting)]<br/>
: [Nicholas Carlini](https://nicholas.carlini.com/), [Florian Tramèr](https://floriantramer.com/), [Eric Wallace](https://www.ericswallace.com/), [Matthew Jagielski](https://jagielski.github.io/), Ariel Herbert-Voss, **Katherine Lee**, [Adam Roberts](https://research.google/people/104881/), Tom Brown, Dawn Song, Ulfar Erlingsson, Alina Oprea, [Colin Raffel](https://colinraffel.com/). Dec, 2020
: runner up [Caspar Bowden award at PETS 2023](https://petsymposium.org/award/winners.php)

Extracting Training Data from ChatGPT [[arxiv](https://arxiv.org/abs/2311.17035)][[blog](https://not-just-memorization.github.io/extracting-training-data-from-chatgpt.html)]<br/>
:   [Milad Nasr*](https://srxzr.com/), [Nicholas Carlini*](https://nicholas.carlini.com/), [Jon Hayase](https://jhayase.github.io/), [Matthew Jagielski](https://jagielski.github.io/), [A. Feder Cooper](https://afedercooper.info/), [Daphne Ippolito](https://daphnei.com/), [Christopher A. Choquette-Choo](https://www.christopherchoquette.com/), [Eric Wallace](https://ericswallace.com/), [Florian Tramèr](https://www.floriantramer.com/), **Katherine Lee**. Nov 2023

Deduplicating Training Data Makes Language Models Better [[arxiv](https://arxiv.org/abs/2107.06499)] [[ACL Oral](https://aclanthology.org/2022.acl-long.577/)]
: **Katherine Lee**\*, [Daphne Ippolito](https://www.seas.upenn.edu/~daphnei/me/category/about-me.html)\*, Andrew Nystrom, [Chiyuan Zhang](https://pluskid.org/), [Douglas Eck](https://research.google/people/author39086/), [Chris Callison-Burch](https://www.cis.upenn.edu/~ccb/), [Nicholas Carlini](https://nicholas.carlini.com/). July 2021

Quantifying Memorization Across Neural Language Models [[arxiv](https://arxiv.org/abs/2202.07646)][ICLR Spotlight]<br/>
: [Nicholas Carlini](https://nicholas.carlini.com/)\*, [Daphne Ippolito](https://www.seas.upenn.edu/~daphnei/me/category/about-me.html)\*, [Matthew Jagielski](https://jagielski.github.io/)\*, **Katherine Lee\***, [Florian Tramèr](https://floriantramer.com/)\*, [Chiyuan Zhang](https://pluskid.org/)\*. Feb 2022 (\*authors alphabetical)

What Does it Mean for a Language Model to Preserve Privacy? [[arxiv](https://arxiv.org/abs/2202.05520)][[FAccT](https://dl.acm.org/doi/fullHtml/10.1145/3531146.3534642)]<br/>
: Hannah Brown, **Katherine Lee**, [Fatemehsadat Mireshghalla](https://cseweb.ucsd.edu/~fmireshg/), [Reza Shokri](https://www.comp.nus.edu.sg/~reza/),  [Florian Tramèr](https://floriantramer.com/). Feb 2022

<!-- Measuring Forgetting of Memorized Training Examples [[arxiv](https://arxiv.org/abs/2207.00099)][ICLR]<br/>: [Matthew Jagielski](https://jagielski.github.io/), [Om Thakkar](http://www.omthakkar.com/), [Florian Tramèr](https://floriantramer.com/), [Daphne Ippolito](https://www.seas.upenn.edu/~daphnei/me/category/about-me.html), **Katherine Lee**, [Nicholas Carlini](https://nicholas.carlini.com/), [Eric Wallace](https://www.ericswallace.com/), [Shuang Song](https://shs037.github.io/), Abhradeep Thakurta, [Nicolas Papernot](https://www.papernot.fr/), [Chiyuan Zhang](https://pluskid.org/). Jun 2022 -->

<!-- Counterfactual Memorization in Neural Language Models [[arxiv](https://arxiv.org/abs/2112.12938)]<br/>: [Chiyuan Zhang](https://pluskid.org/), [Daphne Ippolito](https://www.seas.upenn.edu/~daphnei/me/category/about-me.html), **Katherine Lee**, [Matthew Jagielski](https://jagielski.github.io/), [Florian Tramèr](https://floriantramer.com/), [Nicholas Carlini](https://nicholas.carlini.com/). December 2021 -->

<!-- WT5?! Training Text-to-Text Models to Explain their Predictions [[arxiv](https://arxiv.org/abs/2004.14546)]<br/>: Sharan Narang, [Colin Raffel](https://colinraffel.com/), **Katherine Lee**, Adam Roberts, Noah Fiedel, Karishma Malkan. April, 2020
 -->

Hallucinations in Neural Machine Translation [[NeurIPS IRASL](https://openreview.net/references/pdf?id=B1Muak8L4)] <br/>
: **Katherine Lee**, Orhan Firat, Ashish Agarwal, Clara Fannjiang, and David Sussillo. Dec, 2018

<!-- Is My Prediction Arbitrary? Measuring Self-Consistency in Fair Classification [[arxiv](https://arxiv.org/abs/2301.11562)][[pdf](https://katelee168.github.io/pdfs/arbitrary.pdf)]: [A. Feder Cooper](https://afedercooper.info/), **Katherine Lee**, Madiha Zahrah Choksi, Solon Barocas, Christopher De Sa, James Grimmelmann, Jon Kleinberg, Siddhartha Sen, Baobao Zhang. Jan, 2023 -->

Talkin’ ‘Bout AI Generation: Copyright and the Generative-AI Supply Chain [[ssrn](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4523551)] [[arxiv](https://arxiv.org/abs/2309.08133)][[blog](https://genlaw.org/explainers/talkin.html)]<br/>
: **Katherine Lee**\*, [A. Feder Cooper](https://afedercooper.info/)\*, [James Grimmelmann](http://james.grimmelmann.net/)\*

<!-- Propagation of information along the cortical hierarchy as a function of attention while reading and listening to stories [[Cerebral Cortex](https://www.biorxiv.org/content/biorxiv/early/2018/04/08/291526.full.pdf)] <br/>: Mor Regev, Erez Simony, **Katherine Lee**, Kean Ming Tan, Janice Chen, Uri Hasson. Sep, 2019 -->

## Writing {#writing}

[AI and Law: The Next Generation](https://genlaw.org/explainers/) (2023)
: [The Devil is in the Training Data](https://genlaw.org/explainers/training-data.html) (2023)

[Talkin' 'Bout AI Generation: Copyright and the Generative-AI Supply Chain](https://genlaw.org/explainers/talkin.html) (2023)

[Writing a Google AI Residency Cover letter](https://craffel.github.io/blog/writing-a-google-ai-residency-cover-letter.html) with [Ben Eysenbach](https://ben-eysenbach.github.io/) (2019)

[Submit to Journals](blog/submit-to-journals.html) [[pdf](blog/submit-to-journals.pdf)] (2018)

### Fun writing

[Sourdough Literature Review](blog/sourdough.html) (2020)

## Invited Talks {#invited-talks}

Security
: Panel on Machine Learning, Memorization, and Privacy at [Theory and Practice of Differential Privacy (TPDP)](https://tpdp.journalprivacyconfidentiality.org/2023/), Sep 2023
: [Prosus](https://www.prosus.com/) AI Marketplace, Oct 2023
: Red Teaming Language Models at [Supporting NIST’s Development of Guidelines on Red-teaming for Generative AI](https://www.cmu.edu/block-center/news-events/feb-23-kl-gates-event.html), Feb 2024 [[slides](pdfs/red-teaming-feb-2024.pdf)]
: CHAI, Jul 2024

Generative AI + Law
: Copyright Panel at [Generative AI + Law Workshop @ ICML](https://genlaw.org/), Jul 2023
: The Copyright Law of Generative AI at [Silicon Flatirons Generative AI and Copyright Conference](https://siliconflatirons.org/events/2023-10-06-generative-ai-and-copyright/), Oct 2023
: Berkeley [CS 188.](https://www2.eecs.berkeley.edu/Courses/CS188/) Introduction to Artificial Intelligence, Dec 2023
: [CS + Law](https://computersciencelaw.org/2024-2/program/), Mar 2024
: [28th Annual BTLJ-BCLT Spring Symposium: AI Governance at the Crossroads](https://www.law.berkeley.edu/research/bclt/bcltevents/btlj-bclt-spring2025/), Feb 2025 [[recording](https://bcle.law.berkeley.edu/program?id=85561)]

Memorization in Language Models [[slides](https://katelee168.github.io/pdfs/privacy-slides-dec-2022.pdf)] [[poster](https://katelee168.github.io/pdfs/aies-poster-2022.pdf)][last updated: Dec 2022]
: University of Toronto, May 2022
: [Mosaic ML](https://www.mosaicml.com/), Jul 2022
: GovAI, Aug 2022
: [ML Security & Privacy Seminar ](https://vsehwag.github.io/SPML_seminar/), Aug 2022
: [LEgally Attentive Data Scientists ](https://www.legalityattentivedatascientists.eu/), Sep 2022
: Cornell, NLP Seminar, Sep 2022
: [Cornell, C-Psyd](https://c-psyd.github.io/), Sep, 2022

Privacy
: Why do we care about privacy? at [PPAI](https://ppai-workshop.github.io/), Feb 2024 [[slides](pdfs/why-privacy-feb-2024.pdf)]
: What does Privacy in Language Modeling Mean? [[slides](https://katelee168.github.io/pdfs/lm-privacy-slides.pdf)] at UNC, Apr 2022
: What does Privacy in Language Modeling Mean? [[slides](https://katelee168.github.io/pdfs/lm-privacy-slides.pdf)] at Cornell, Apr 2022 

Dataset selection
: [Mosaic ML](https://www.mosaicml.com/), Sep 2023

Workshops
: Co-organized [GenLaw ICML 2024 Workshop](https://www.genlaw.org/2024-icml), Jul 2024
: Co-organized Evaluating Generative AI Systems, April 2024
: Co-organized [GenLaw ICML 2023 Workshop](https://blog.genlaw.org/2023-full-report.html) on Generative AI and Law, Jul 2023 [[report](https://arxiv.org/abs/2311.06477)]

<!-- ## Service
* Organized the Generative AI and Law Workshop ([GenLaw '23'](https://genlaw.org/)) at ICML 2023.
* Helped organize [WELM workshop](https://welmworkshop.github.io/) at ICLR 2021 and moderated a panel discussion on "Bias, safety, copyright, and efficiency"
* Reviewer for NeurIPS, ICML. -->

## Fun!
In my free time, I enjoy making stuff. Sometimes this is [pottery](https://www.instagram.com/paw_projects/), [sourdough](https://www.instagram.com/nomnomnom.s/), or knitting/crocheting. I also enjoy being outdoors, listening to [jazz](https://open.spotify.com/playlist/37i9dQZF1DX4wta20PHgwo?si=mkKIGDzISB61q_tBGndEiw), and dancing. Sometimes all at the same time! I used to live [here](https://ludwigschubert.github.io/twotwelve.house/).

During my undergrad in Operations Research at Princeton, I had great fun learning about how real neural networks (brains!) take in the world with [Jonathan Pillow](https://pillowlab.princeton.edu/) and [Uri Hasson](https://www.hassonlab.com/).

In the more distant past, I’ve also solved for optimal seating arrangements at Google, and I spotted ships at bay with hyperspectral sensors at the Naval Research Lab in DC.


