# Katherine Lee
<img style="padding: 15px" src="images/me.jpg" width="180" border="50" align="right"/>
<p></p>
Hello! 
\

I'm currently a Research Engineer at Google Brain Research in San Francisco, CA. 

\

I'm broadly interested in building machine learning systems we can trust. This means figuring out when models are untrustworthy, what knobs change their behavior, and developing interactions and visualizations to learn where strengths and weaknesses of models are. 

## Writing
[Writing a Google AI Residency Cover letter](https://craffel.github.io/blog/writing-a-google-ai-residency-cover-letter.html) with Ben Eysenbach (2019)

[Submit to Journals](blog/submit-to-journals.html) [\[pdf\]](blog/submit-to-journals.pdf) (2018)

## Fun!
In my free time, I enjoy making stuff. Sometimes this is [pottery](https://www.instagram.com/paw_projects/), sourdough, or knitting/crocheting. I also enjoy being outdoors, listening to jazz, and dancing. Sometimes all at the same time!


***
<footer>
<div style="float:left; width: 80%;">
Website generated with [Pandoc](https://pandoc.org) with [pandoc.css](https://gist.github.com/killercup/5917178)
</div>
<div style="float:left; width: 20%; text-align:center;">
[Google Scholar](https://scholar.google.com/citations?user=bjdB4K8AAAAJ&hl=en)

[Twitter](https://twitter.com/katherine1ee)

[Instagram](https://www.instagram.com/paw_projects/)
</div>
</footer>
