# Katherine Lee
<p align="right"><sup>(she/her)</sup></p>
<div><img style="padding: 25px" src="images/me.jpg" width="200" border="50" align="right"/></div>
<div style="text-align: justify">Hello! 

I'm currently a Research Engineer at Google Brain Research in San Francisco, CA.

<!-- I'm broadly interested in building machine learning systems we can trust. This means figuring out when models are untrustworthy, what knobs change their behavior, and developing interactions and visualizations to learn where strengths and weaknesses of models are.  -->
People are so cool! People interacting are even cooler! I'm excited to learn more about _us_ and how algorithms shape our lives. What affects the decisions we make? What motivates someone to speak up? What would change someone's mind? What kinds of decisions can algorithms help with, and which should we leave algorithms out of? What kinds of objectives, political or social, can we, or can we not write down?

At Brain, I've spent some time figuring out how trustworthy our machine learning systems are and how much variance there is in different training procedures. 

Before that, I had great fun learning about how real neural networks (brains!) take in the world with [Jonathan Pillow](https://pillowlab.princeton.edu/) and [Uri Hasson](https://www.hassonlab.com/) during my undergrad in Operations Research at Princeton. 

You can find me on the internet: [Twitter](https://twitter.com/katherine1ee), [Google Scholar](https://scholar.google.com/citations?user=bjdB4K8AAAAJ&hl=en), [Goodreads](https://www.goodreads.com/user/show/44386744-katherine)


</div>
## Recent work
T5: Exploring the Limits of Transfer Learning with a Unified Text-to-Text Transformer \[[arxiv](https://arxiv.org/abs/1910.10683)\]<br/>
: Colin Raffel, Noam Shazeer, Adam Roberts, **Katherine Lee**, Sharan Narang, Michael Matena, Yanqi Zhou, Wei Li, Peter J. Liu. Oct, 2019

Hallucinations in Neural Machine Translation \[[NeurIPS IRASL](https://openreview.net/references/pdf?id=B1Muak8L4)\] <br/>
: **Katherine Lee**, Orhan Firat, Ashish Agarwal, Clara Fannjiang, and David Sussillo. Dec, 2018

## Writing
[Writing a Google AI Residency Cover letter](https://craffel.github.io/blog/writing-a-google-ai-residency-cover-letter.html) with Ben Eysenbach (2019)

[Submit to Journals](blog/submit-to-journals.html) \[[pdf](blog/submit-to-journals.pdf)\] (2018)

### Fun writing
[Sourdough](blog/sourdough.html) (2020)

## Fun!
In my free time, I enjoy making stuff. Sometimes this is [pottery](https://www.instagram.com/paw_projects/), [sourdough](https://www.instagram.com/nomnomnom.s/), or knitting/crocheting. I also enjoy being outdoors, listening to [jazz](https://open.spotify.com/playlist/37i9dQZF1DX4wta20PHgwo?si=mkKIGDzISB61q_tBGndEiw), and dancing. Sometimes all at the same time!

In the more distant past, I’ve also solved for optimal seating arrangements at Google, and I spotted ships at bay with hyperspectral sensors at the Naval Research Lab in DC.

***
<footer>
<div style="float:left; width: 80%;">
Website generated with [Pandoc](https://pandoc.org) and [pandoc.css](https://gist.github.com/killercup/5917178). 
\
^ It's super easy to use and flexible, and you should use it too!
</div>
<div style="float:left; width: 20%; text-align:center;">

</div>
</footer>
