---
title:  '  hi'
---

[Call it like it is](misc/menstruation.html) (2021)

[The Rationalist Community circa 2016-2018 and its growth](misc/rationalist-community.html) (2021)

[Creating Safety](misc/safety.html) (2021)

[Yes, and](misc/yes-and.html) (2021)

[How to fill a water balloon with paint and then paint with it](misc/paintballs.html) (2021)

[Bye, SF](misc/bye-sf.html) (2021)

[Slow Down](misc/slow-down.html) (2018)

[Learning to fail](misc/learning-to-fail.html) (2017)

<p style="text-align:right">[Katherine Lee](https://katelee168.github.io/)</p>
