---
title:  '  hi'
---

[How to fill a water balloon with paint and then paint with it](blog/paintballs.html) (2021)

[Learning to fail](blog/learning-to-fail.html) (2017)

<p style="text-align:right">[Katherine Lee](https://katelee168.github.io/)</p>
