---
title:  'Yes, and ...'
---

Learning to write formulas in Excel was my first conscious brush with automation. 
I daydreamed my chores into the hands of machines.
    Need another transition here
When I read Diamond Age, where a girl learns from a book, the Primer, that generates lessons for her based on her life experiences, I wanted it. 

In 2017, a new architecture for neural networks<!-- (maybe say AI) --> was created, and tasks like summarizing a news article suddenly seemed with reach. It was called the Transformer, and I was starting a new job at research lab where it was invented^[The first month I was there, I must've attended five talks by the authors of the Transformer, and I have to admit, I didn't understand why this would work, and the previous state-of-the-art technique, called sequence to sequence models, did not. Years later, I'm still not sure there's a reason why Transformers work better, except that they have done so.]. It seemed like it would be possible to build the literal Primer in a few short years. Colleagues in my building rushed to create its predecessors, and I froze. 

An important part of the Primer is that its lessons are tailored to the individual. Summarizing a news article requires knowing what the reader is hoping to come away from the article with. If they're looking for the facts of the case, which facts were relevant? And also, what is a fact? A single summary could not give you the salient takeaways. Actually, it's the opposite, communicating all interesting parts of an article might require expanding the article to bring in additional context. So while the Primer was maybe the inspiration, the actual products that were deployed set their goals much shorter than surfacing tailored information to the reader. The language tools that have come closest to this are: SmartSummaries that mine your emails for actionable takeaways^[cite, and give example], or predictive coding^[cite, microsoft / openai]^[There are many other AI-based language products, like AI Dungeon that are astounding and wildly transformative.].

At work and at weekend, SF parties, I waded through conversations: "Wouldn't it be so cool if we could...," "Oh! And then we could..." 
The conversations would spin out as the participants discussed the technical challenges of implementing the new task. 

And I would respond with "sure, but..."

<!-- For a moment there, I believed that you could make any justification sound plausible. The seeming ease with which people around me crafted narratives to justify their work made me feel completely unmoored from morals.  -->

... how much data would we have to collect about someone in order to tailor a summary to them? Couldn't it be a violation of their privacy? Sure, but learning is awfully close to persuasion, and persuasion is a dangerous, powerful tool. Sure, but who gets to decide what's important for people to learn? Shouldn't that decision be made by the community?

How come "yes, and"s were allowed to have fun with their work? 
How come they weren't thinking about the "but"s?
I wanted to have fun with my work. 
Somehow in the decade between my first foray into programming and today being confronted with the opportunity to realize those dreams, I didn't know if I wanted it anymore. 

I learned this is another form of privilege--the ability to turn a blind eye to the effects your actions have on others without it meaningfully impacting your life. 

I wasn't the only "sure, but" in the room.
They came in all forms: 
<!-- AI researchers demonstrating how facial recognition algorithms struggle with black faces^[cite], -->
AI researchers arguing that these algorithms are no more than parrots that return whatever data they were used to train on^[cite stochastic parrots],
philosophers formalizing how people make decisions about what level of privacy are expected in a given situation^[contextual integrity],
researchers that worked to us to specify nuanced objectives to AI agents through offering feedback^[cite],
and sociologists pulling from decades of work on the ethics and challenges of collecting data from humans^[cite].
When I started to look, I was slapped in the face by my own ignorance. 
There was decades of work from sociologists, historians, and librarians on the ethics and challenges of data collected from, or left behind by humans. 
Data availability and the process through which that data was collected would influence both the types of research that were possible and the systems that were built.
To add fuel to fire, 

gas and breaks
both people can play both roles
being breaks is not intrinsic to certain disciplines


AI researchers pulling from decades of literature on technology and sociology to describe how , 
They worked together: 
the formalized constraints people place on social interactions that philosophers develop^[example: contextual privacy] are used by researchers.
It amazed me that they came from such different 
philosophers working on ways to formalize the constraints 
and decades of work in technology studies that 
philosophers writing about how context dictates what level of privacy we expect in a given interaction^[cite],


I think the "yes, and"s ought not to be pitted against the "sure, but"s. Let's take my literal work for example. How does one simultaneously explore the technology while making room for the sociological changes that must happen.
The two work hand in hand.
The ways society and its people will use technology changes the way it should be designed and the open problems that it has.
This is not a novel thought to any designer in the room. 







## Misc stuff
I didn't end up working on summarization, but I have spent the last four years working with Transformer models in all different capacities. 

When it seemed like I finally had the opportunity to work on the literal Primer, I froze. There were people sitting in the same building working on it, and I wanted to be as far from it as possible. This from a girl who spent the last decade hyper-optimizing her life, and constantly dreaming of automation and taking as much work off her hands as possible. What was going on?
 It's impossible to package up growth into bite
Inspiration is also not always predictable. ^[variance in kindle highlights?].

Creating any work requires knowing who the audience is, though sometimes it's an implicit audience.


It seems implausible to chart a path of incremental inspiration, even though a small thing at the right time can be meaningful. 
The problem is then is making summarization a fixture in our lives. 
The problem thus is more with making summarization a fixture in our lives, replacing news articles entirely. But what actually is the problem with that? Meaning is what we ascribe to it. What we give up in control here, we can take control of in other ways. So we read fewer news articles, perhaps we'll read more summaries. Perhaps we'll seek out facts through another system designed to extract only that. Perhaps these systems will become so advanced that we can 
Humans are ceaselessly resourceful. But the best restaurants source the best ingredients, because while you can overcome, why should we expend energy overcoming instead of thriving?

Every innovation in human communication changes human communication: spoken language, Written language, mail, and email. Today, whether people type on their phone, use a computer, or use the swipe keyboard on a phone changes the way they use language^[cite]. 

Am I just trying to justify what is impossible to justify?
Is it completely morally corrupt?

Like every little girl, I used to dream of a robot assistant that would hand me the color of paint I wanted to use before I had completed my thought. 
I imagined it following me around, prompting me with little todos and advice.
Somehow, coming from my robotic assistant that felt desirable, but coming from my mother, less so

Later the phrase "slight of hand" seemed extremely relevant. 

And then I would respond with how I wasn't sure that adding technology was the right answer to that problem, since it seemed like it was a social problem, or that to get the technology right, you would need to know an awful lot about the social context the technology would be operating in. 

I spent two years only seeing the potential dangers. 
Around me, "yes, and"s swirled.

I had a love/hate relationship with planning the meta, frequently feeling like I was spending too much time designing courses of action and not enough executing on it.

## Misc footnotes
^[I suppose my own mental state also played into my perceptions of the world around me, so it's worth saying that throughout this period, I was depressed. Though to be frank, I can only say the depression was correlated. Not that my depression solely influenced these perceptions, or that these perceptions didn't fuel my depression.]

<p style="text-align:right">July 1, 2021</p>
<p style="text-align:right">[Katherine Lee](https://katelee168.github.io/),  [misc ↩](https://katelee168.github.io/misc)</p>
