---
title:  'Sourdough Literature Review'
author:
- Katherine Lee
---
<p style="text-align:right">May 7, 2020</p>
_This post is under construction. I'd love your feedback! It's intended to be literally everything I know about sourdough._

I have watched _far too many_ videos about sourdough, read far too many books about sourdough, blogs about sourdough, baked more loaves of bread than I actually wanted to eat. I didn't choose this life^[No actually, my starter was gifted to me through jam container left in the fridge by a coworker via his intern.], but since I have sunk a large amount of my life into learning about sourdough, you can benefit unleashing a researcher into a new field.

<div>
  <img style="margin-left:25%; width:50%" src="images/bread.jpg">
  <p style="text-align: center;">[_click me for more pretty pics_](https://www.instagram.com/nomnomnom.s/)</p>
</div>



Before reading on, ask yourself if you're making sourdough to eat bread, or if you're making sourdough to give yourself something to do. You'll probably take different approaches! If you just want bread, then you'll be pleased to know that almost nothing _really_ matters. If you want to give yourself something to do, you'll be pleased to know that _everything_ matters a whole lot! It just depends on what your standards are. It's also totally okay to switch around between "give me bread" and taking the temperature of your room to time your folds.

> **If you just want bread**, here's an awesome casual video for overnight sourdough from [Northwest Sourdough](https://www.youtube.com/watch?v=qsG9z_aR4Tc), one from [Foodgeek](https://www.youtube.com/watch?v=ApANfdFdyz0), and [another](https://www.youtube.com/watch?v=58RoHmgeojc) just to show you how much nothing matters and everything is fungible and you'll definitely get tasty bread. 
> 
> If, on the other hand, you want to **busy your hands and minds** with super detailed and complicated recipes, I recommend [Tartine's country loaf](https://cooking.nytimes.com/recipes/1016277-tartines-country-bread), [The Perfect Loaf](https://www.theperfectloaf.com/beginners-sourdough-bread/), [Joshua Weissman](https://www.youtube.com/watch?v=jJpIzr2sCDE), [Jack Bakes](https://www.youtube.com/watch?v=vmb0wWKITBQ), and [Foodgeek](https://www.youtube.com/watch?v=Znv99QbfWGs).

So, let's get to it. I'll give you my [bread routine](#basic-loaf), walk you through [tips and tricks](#tips) I've picked up, dump a lot of [details](#details), talk about [variations](#variations), [starter maintenance](#starter), what to do with your [discard](#discard), and point you to [other people](#resources) who have baked even more loaves of bread than I have. 

## Assumptions 
I like baking smaller loaves more frequently because we're currently in quarantine, and I have nothing else to do. Baking at least keeps my fingers busy. This makes a small hunk of bread that my two roommates and I could devour in one sitting. It also makes 3 personal sized pizzas (that we, again, finish in one sitting), or one loaf of focaccia that we have also totally finished in one sitting, topped with garlic and avocados.

## Super basic loaf <a name="basic-loaf"></a>
I make my dough the day before because I like it a little tangier, but you can totally skip the fridge and go ahead and bake. 

* 9am: Feed starter 33g water and 33g flour for a total of 66g starter + whatever was in the container already. This is called a levian^[My roommate says it's pronounced luuuu-von.].
* 12pm: Smell your levian. If it smells sweet but not sour, that's the perfect time to bake!
* 12:01pm: Hydrate your dough (autolyse)
    * 233g water at 90F into a medium bowl
    * Dissolve 66g levian into the water, save the rest--that's your remaining starter!
    * Add 300g AP flour and 33g whole wheat flour.
    * Roughly mix^[I just do this with a spoon. It's pretty easy to mix from the center first, then go and incorporate the rest of the flour on the outside. This makes it easier to hydrate all the dough]
* 1pm (aka, after lunch): Add salt + more water
    * Add 17-20g more water and 9g salt
    * Squish the water and salt and dough in between your fingers until well incorporated
    * If it doesn't come together well, use your fingers as the claw on a mixer and stir it around until it comes together.
    * Move it into a plastic tupperware, put the lid loosly on, and leave it in a warm-ish spot. The plastic tupperware is oddly helpful! More on this later.
* Afternoon: every so often when you wander into the kitchen (every 30min-1hr), give that dough the nice stretch&fold! Your dough should be nice and loooooose. When you pick up a corner to stretch, it should drible back into the bowl. I pick up the corner, let the stretched-out corner fall back onto the dough, rotate the tupperware, and repeat with the next corner. 
    * After 2-3 turns, I start doing coil rolls. I put my hands under the dough, and pick it up, letting one side tuck under the dough as I put it back down. Then turn it 90deg, pick it up, let one side tuck under the dough as I put it back down, repeat. 
* After 4-ish turns, I preshape, wait 30 min, shape, and put it in a flour-dusted, towel-lined bowl. Put that in a plastic bag, and put it in the fridge. Since this move is complicated to describe in text, watch this video:
    * Key STUFF: 
        * You're building the tension on the surface of the dough. If you break that tension, you'll be able to see it in the dough because instead of that nice smooth surface, you'll see the gluten strands. 
        * If helps to touch the surface of the dough between preshaping and shaping. If it's still tacky, then wait a little longer for the surface to dry a little more. 
* Next day (4pm for 6pm dinner for me): preheat oven to 500F, with pizza stone & the bottom of a dutch oven (or something that can go over your bread).
* 4:30pm: Take the pizza stone out of the oven. Take the dough out of the fridge and invert it directly onto the stone. Slash it with a sharp knife, pop the bottom of the dutch oven upside down over the dough, and put the contraption back in the oven. Lower the temp to 450, set a timer for 20 min. 
* Take the lid off, and bake for another 20-25 min depending on how dark you like your bread.
* Take bread out of the oven, let it cool on a rack (or in a pinch, on a pair of chopsticks). Wait 30 min before digging in with some olive oil at hand.

## The most important tips <a name="tips"></a>
* Sweet smelling starter! I used to think it would be better to just use more starter, or use sour-ish starter for more flavor. Apparently more starter just means that the dough will ferment faster. More sour-ish starter means the starter is past its prime. Don't do that.
* Adding additional water when adding the salt makes it a lot easier to incorporate the salt, helps bring the dough together, and is a good time to adjust for a little more or a little less water. 
* The plastic tupperware apparently helps the dough retain warmth. It also makes it wayyy easier to fold because it doesn't cling to the dough as much as the metal does. I will also sometimes pre-shape the dough while it's in the container by dragging my hand along the side of the dough while scooping the bottom and pushing it off to one side. This helps tighten the surface of the dough!

## Detailed commentary <a name="details"></a>
* Variations on autolyse: Some people dissolve the starter into the water, some do the autolyse with just water and flour (no starter), some do autolyse with salt + starter + water + flour. Apparently the salt makes fermentation go slower, but honestly I've tried all of the above methods, and it really doesn't seem to matter. If you're in a pinch for time, then just throw everything together. 
* Time is everything. Time during the autolyse makes it way easier to bring all the flour together and works better than kneeding the dough. Just chill! It's a very SF dough. 
* I didn't understand how loose the dough would be. If you get nice gluten formation, then you can wiggle the dough and it'll just stretch nice and long. When I first started baking, the dough would break on me, or be too dry. I think the difference now is I wait for the dough to relax.
* Using the pizza stone with an inverted dutch oven works better for me. It makes it easier to dump the dough onto a surface without sides and makes it easier to score.
* When scoring the dough, you can use your fingers to hold down the side you're starting the slash from. This gives a little more tension.
    * Apparently if you want an ear on your loaf (which you do), then you ought to score the dough with your knife almost parallel to the countertop. 
    * Dull knives are really sad for this. The serrated knife worked better than a dull knife. 
* You can add other things to your sourdough! I tried adding purple sweet potato. This was awesome & so easy. Add any mixins when you add salt. Other people say after the first fold. Whatever. The potato dissolved into the dough and the resulting loaf was purple, extra sour^[My hypothesis is the sugar in the potato was more yummy to the yeast and it was more active. It certainty rose more!], and sticky spongy. It did not, however, really taste like potato.

Highly recommend Tartine's writeup about it (which this is basically a summary of). Just follow what they did. The book has more thoughts about why it works, and The Perfect Loaf, and Joshua Weissman are also great, but way more steps than are actually needed. I'd only read them if you get bored of your bread and want to start fine-tuning things. 

When we weren't in quarantine, I did things very differently, and it also worked out great & didn't take up too much time: about 1 hr active time start to finish. 

## Variations <a name="variation"></a>
Maybe I'll do another post about pizza. For now, pizza dough & foccacia can be made with literally the same stuff. For pizza, you can skip the final shape. For foccacia, you can proof the dough on the sheet pan for a few hours before you bake (remember to oil the sheet pan before you add the dough!).

## More detailed starter notes <a name="starter"></a>

Keeping starter around is such a chore. Either just keep it in the fridge and feed it the night before you want to use it, or steal it from your neighbor when you want to bake. We've gone a full three weeks without feeding it in the fridge and it's, like, okay. 

Keeping starter around can also be fine. I keep my starter on the counter and feed it every day. It totally owns me and my morning routine. But if you bake more than once a week, then it seems worth it since you'd have to feed it the night before you bake anyways.

*Keep it minimal.* I keep just 30g of starter at any given time on the counter. I also keep a jar in the fridge for discard. Every morning, I:

* Move 20g of starter into the "discard jar" and put it back in the fridge.
* Pour 10g of water into the starter dish, stir it around to dissolve the starter in the water
* Add 10g of flour to the starter dish. 

I bet you could totally keep around even less if it made a meaningful difference to your flour stash.

## Use your discard <a name="discard"></a>
[NYT  Cooking](https://www.nytimes.com/2020/04/28/dining/sourdough-discard.html) said it best:

> "Sourdough starters are generally a 1:1 ratio of flour to water by weight. Half of the weight is flour, and half of the weight is water. To add discard to any baked good, subtract the flour and water (or liquid) amounts in the discard from the original recipe. For example, if you want to add 115 grams discard to a recipe, remove 57 grams of flour and 57 grams liquid from the amounts the recipe originally called for."

When the "discard jar" gets to like a 1/2 cup or so (I keep mine in a mason jar, so it's easy to see the quantity of it), I go on King Arthur Flour and look up some [discard recipes](https://www.kingarthurflour.com/search?query=discard&algolia-index=recipe_index&hide-tabs=1). Here are some I've liked:

- Crumpets: literally add (to that same jar): 4g sugar, 4g salt, and 2g baking soda to 1 cup starter (260g). Then oil a non-stick pan, and pour it on. When large bubbles form and the pancake sets, flip it over. So simple. So tasty^[Apparently my friend just straight up pours the starter onto the pan and then eats that with maple syrup. She claims to like it. I tried that once, and it was too sour for me. My theory is the baking soda reacts with acidity and it makes the final crumpet less sour. So don't skip it! It also majorly helps with rise. I totally don't have a "crumpet former" but you can use one, it's still delicious and crisp on the bottom.].
    * For variations: add scallions (or green garlic)^[The farmer's market has been teasing us lately. If you know me, you know I looooove garlic, but every week it's just green garlic :(] and/or sesame seeds.
- Buttermilk, sourdough pancakes. And instead of buttermilk, using the leftover whey we had from turning our on-the-way-out milk into cheese. 
- Banana bread: Follow [Joshua Weissman's banana bread](https://www.youtube.com/watch?v=ToBMly0nx4Q).
    * Make this vegan by just leaving out the egg and swap out the butter with canola oil. Here are some ingredient quantities for vegan banana bread: bananas (3), vanilla extract (4g), sugar (14g), brown sugar (50g), canola oil (36g), ap flour (150g), starter (90g), baking soda (1tsp), cinnamon (1tsp), salt (3g), chocolate chips/walnuts/oats (to taste!!). Bake at 350 for 45 min then check if it needs 5 more min.
- Coooooookies! Follow [Joshua Weissman again](https://www.youtube.com/watch?v=wyuec0PPz68).
- Just add it to random stuff. Works great, 10/10, would experiment again. My roommate made lentil pancakes with the sourdough discard that we had just kept in the fridge for a while, and the discard got pretty active and started eating the pancakes, so I'd be aware that it'll keep fermenting if you wait for a while between adding the starter and cooking the dough. If you don't want it to ferment/rise, go ahead and use the dough immediately and the discard just adds a little flavor and saves on some flour. If you want it to ferment/rise, then let it linger for a while! Maybe in your fridge while you forget about it for a few days... oops. 

## Additional resources <a name="resources"></a>
* [Jim Lahey, Elasticity and Bread: Science and Cooking Public Lecture Series 2015](https://www.youtube.com/watch?v=ZWrSK3Pjmj4)
* Foodgeek makes awesome videos answering questions like: "[Can you bake sourdough bread with all-purpose flour?](https://www.youtube.com/watch?v=6UPdNUbk8Qg)," and "[Should you stretch and fold your dough? What is the best way to knead?](https://www.youtube.com/watch?v=Lz9CO1PJ0sM)". Get all your questions answered!!
