---
title:  'Sourdough Literature Review'
---
[home ↩](https://katelee168.github.io/)
<p style="text-align:right">May 7, 2020</p>
<p style="text-align:right">[Katherine Lee](https://katelee168.github.io/)</p>

Welcome to sourdough land! It's tangy, blistery goodness. And honestly, once you've gotten into a routine with it, it's pretty mess-free!

There's a heck of a lot of resources about baking sourdough, and it's hard to figure out what the difference is between recipes, and which video to watch, and what matters & what does, and what a poolish is, ...

But I've done all that for you! Here's a survey of some of the best resources out there for your reading pleasure.^[Yes, I've read all of this. Don't judge! It's my version of unwinding.] 

<div>
  <img style="margin-left:25%; width:50%" src="images/sourdough/daylen.jpg">
  <p style="text-align: center;">[_click me for more pretty pics_^[Photo taken by <a href="https://www.instagram.com/daylenyang/">Daylen</a>!]](https://www.instagram.com/nomnomnom.s/)</p>
</div>

Before reading on, ask yourself if you're making sourdough to eat bread, or if you're making sourdough to give yourself something to do. You'll probably take different approaches! If you just want bread, then you'll be pleased to know that almost nothing _really_ matters. If you want to give yourself something to do, you'll be pleased to know that _everything_ really matters! It just depends on what your standards are. It's also totally okay to switch around between "give me bread" and taking the temperature of your room to time your folds more accurately.

> **If you just want bread**, here's an awesome casual video for overnight sourdough from [Elly's Everyday](https://www.youtube.com/watch?v=KkA8JUmLT8k&t=1288s)^[Seriously, start here. It's the easiest, least finicky recipe I've tried], one from [Northwest Sourdough](https://www.youtube.com/watch?v=qsG9z_aR4Tc), and [another](https://www.youtube.com/watch?v=58RoHmgeojc) just to show you how much nothing matters and everything is fungible and you'll definitely get tasty bread. 
> 
> If, on the other hand, you want to **busy your hands and minds** with super detailed and complicated recipes, I recommend [Tartine's country loaf](https://cooking.nytimes.com/recipes/1016277-tartines-country-bread) or [The Perfect Loaf](https://www.theperfectloaf.com/beginners-sourdough-bread/). 
> 
> If you fall far, far down the sourdough rabbit hole, [Flour, Water, Salt, Yeast](https://kensartisan.com/flour-water-salt-yeast) is hands down the best thing ever^[Don't get me wrong, I love Tartine's bread. I love the strong sour, and slightly sticky bread. Flour, Water, Salt, Yeast is a far more comprehensive book and includes how to debug your dough, what the parameters for baking are, how to compare recipes--things every baker could want to know about dough. You should seriously read it, its great bed time reading.]. 

So, let's get to it. I'll give you my [bread routine](#basic-loaf), walk you through [tips and tricks](#tips) I've picked up, dump a lot of [details](#details), talk about [pizza and foccacia](#variations) , [starter maintenance](#starter), what to do with your [discard](#discard), and point you to [other people](#resources) who have baked far more loaves of bread than I have. 

## Super basic loaf <a name="basic-loaf"></a>
The only things you _really_ need to get started are: flour, salt, and a kitchen towel. Life is way nicer if you also have a kitchen scale, plastic tupperware, and a dutch oven. Then, the next things to get are a bench scraper, a [bread lame](https://en.wikipedia.org/wiki/Lame_(kitchen_tool)), and a [banneton](https://shop.kingarthurflour.com/items/round-brotform)^[You can also get all of these things on Amazon, but are we still speaking to Amazon?]. Everything else is optional. 

This is my annotated version of [Tartine’s recipe](https://cooking.nytimes.com/recipes/1016277-tartines-country-bread)^[I had tried sooooo many different bread recipes, and I started writing down the franken-recipe I ended up with, but honestly, I just like Tartine's best.]. I like to spread it out over two days to get a longer proof which makes the bread a little tangier, but you can also totally skip the fridge and go ahead and bake. Also, I like baking smaller loaves more frequently because we're currently in quarantine, and I have nothing else to do. Baking at least keeps my fingers busy. This makes a small hunk of bread (1/4 Tartine's recipe) that my two roommates and I could devour in one sitting. It also makes 3 personal sized pizzas (that we, again, finish in one sitting), or one loaf of focaccia that we have also totally finished in one sitting, topped with garlic and avocados.

* 9am: Feed starter 33g water and 33g flour for a total of 66g starter + whatever was in the container already. This is called a levain^[My roommate says it's pronounced luuuu-von.].
* 12pm: Smell your levain. If it smells sweet but not sour, that's the perfect time to bake! You can also do the float test^[Spoon some of your starter into some warm water. If it floats, it's active and good to go.]
* 12:01pm: Hydrate your dough (autolyse)
    * 233g water at 90F into a medium bowl
    * Dissolve 66g levain into the water, save the rest--that's your remaining starter!
    * Add 300g AP flour and 33g whole wheat flour.
    * Roughly mix^[I just do this with a spoon. It's pretty easy to mix from the center first, then go and incorporate the rest of the flour on the outside. This makes it easier to hydrate all the dough]
* 1pm (aka, after lunch): Add salt + more water
    * Add 17-20g more water and 9g salt^[The second addition of water here is game changing. The dough really comes together nicely and it makes the salt a lot easier to incorporate.]
    * Squish the water and salt and dough in between your fingers until well incorporated
    * If it doesn't come together well, use your fingers as the claw on a mixer and stir it around until it comes together.
    * Move it into a plastic tupperware, put the lid loosely on, and leave it in a warm-ish spot. The plastic tupperware is oddly helpful! More on this later.
* Afternoon: every so often when you wander into the kitchen (every 30min-1hr for the next 3-4 hrs), give that dough the nice stretch&fold! Your dough should be nice and loooooose, like in this [video from Tartine](https://www.instagram.com/tv/B-5MBczBu10/?utm_source=ig_web_copy_link). When you pick up a corner to stretch, it should dribble back into the bowl. I pick up the corner, let the stretched-out corner fall back onto the dough, rotate the tupperware, and repeat with the next corner. 
    * After 1-2 turns, I start doing coil rolls, like in this [video from Tim Passmore](https://www.instagram.com/p/B-_oZepJYns/?utm_source=ig_web_copy_link). I put my hands under the dough, and pick it up, letting one side tuck under the dough as I put it back down. Then turn it 90deg, pick it up, let one side tuck under the dough as I put it back down, repeat. 
* After 4-ish turns, I preshape, wait 30 min, shape, and put it in a flour-dusted, towel-lined bowl. Put that in a plastic bag, and put it in the fridge. Since this move is complicated to describe in text, watch this [video from the San Francisco Baking Institute](https://www.youtube.com/watch?v=vEG1BjWroT0). 
    * Things to take note of: 
        * You're building the tension on the surface of the dough. If you break that tension, you'll be able to see it in the dough because instead of that nice smooth surface, you'll see the gluten strands. 
        * The time in between the preshaping and shaping is for the surface to dry out a little and for the dough to relax again. If the dough is super sticky, then wait a little longer to do the final shaping. If it's just a little tacky, that's fine,
* Next day (4pm for 6pm dinner for me): preheat oven to 500F, with pizza stone & the bottom of a dutch oven (or something that can go over your bread).
* 4:30pm: Take the pizza stone out of the oven. Take the dough out of the fridge and invert it directly onto the stone. Slash it with a sharp knife, pop the bottom of the dutch oven upside down over the dough, and put the contraption back in the oven. Lower the temp to 450, set a timer for 20 min. 
* Take the lid off, and bake for another 20-25 min depending on how dark you like your bread.
* Take bread out of the oven, let it cool on a rack (or in a pinch, on a pair of chopsticks). Wait 30 min before digging in with some olive oil at hand.

## The most important tips <a name="tips"></a>
* **Sweet smelling starter**! I used to think it would be better to just use more starter, or use sour-ish starter for more flavor. Apparently more starter just means that the dough will ferment faster. More sour-ish starter means the starter is past its prime. Don't do that.
* Adding **additional water** when adding the salt makes it a lot easier to incorporate the salt, helps bring the dough together, and is a good time to adjust for a little more or a little less water. 
* The **plastic tupperware** apparently helps the dough retain warmth. It also makes it wayyy easier to fold because it doesn't cling to the dough as much as the metal does. I will also sometimes pre-shape the dough while it's in the container by dragging my hand along the side of the dough while scooping the bottom and pushing it off to one side. This helps tighten the surface of the dough! You can also totally do all the mixing in the plastic tupperware as well. 
* **Finger poke test** If your bread is nicely proofed, then it should spring back slowly when you poke a finger in it. If your finger indent doesn't disappear, then it's overproofed, if it springs back quickly, it needs more time. 
* **Time** is everything. Time during the autolyse makes it way easier to bring all the flour together and works better than kneading the dough. Just chill! It's a very SF dough^[Also, most of the stuff I've read around sourdough is all about learning about your own preferences, your specific dough, your kitchen, your climate--very SF. Maybe I've spent too much time in SF, but I feel like this is good life advice. Don't just follow the formula, muck around with stuff and learn what good bread feels like to you.]. 

## Detailed commentary <a name="details"></a>
* Sourdough isn't really a knead thing. Mostly the time and fermenting do the gluten development for you. But if you want to watch someone knead sourdough for 40 min straight, [Jim Lahey](https://www.youtube.com/watch?v=ZWrSK3Pjmj4) has an excellent lecture on what kneading does to dough. 
* There are several names/methods for pre-fermenting the dough: poolish, biga, levain, etc. idk, it feels like there's just lots of [different ways](https://www.thekitchn.com/what-the-difference-between-sourdough-starter-250218) of doing things because people from different regions of the world did things differently and they all work but maybe give different flavors. Experiment!^[Flour, Water, Salt, Yeast goes into the differences in more detail between poolish and biga]
* There are also a few different timings for when to add the starter and salt. Some simple recipes dissolve both the starter and salt into the water before adding flour. Some do an autolyse (hydrating the flour), then add in the starter and then add in the salt. Some dissolve (as I do above) the starter into the water, then add the salt separately later. I'm sure it matters, but if you're in a pinch for time, I like the starter + water + flour approach best because I don't have to come back in 30min-1hr to add the starter in, then another 30min-1 hr to add the salt in before doing any folds!
* Salt makes fermentation go slower.
* Using less starter will also make fermentation go slower, which means it'll have more time to build flavor. I used to think that more starter = more flavor & a faster rise time, what's not to like about that! Apparently not. 
* Bakers percentage is the percentage of your ingredient to all purpose. So if you use 700g water with 1000g all purpose flour, then your dough is 70% hydrated. You can also use bakers percentages to talk about all your other ingredients, like your salt, or whole wheat flour. 
* Don't be a hero. A 65% hydration dough is awesome. Start there! Like this one: [Elly's Everyday](https://www.youtube.com/watch?v=KkA8JUmLT8k&t=1288s). 
* I didn't understand how loose the dough would be. If you get nice gluten formation, then you can wiggle the dough and it'll just stretch nice and long. When I first started baking, the dough would break on me, or be too dry. I think the difference now is I wait for the dough to relax.
* On baking & oven spring: Oven spring, aka, the awesome springy rise when your dough first goes into the oven, is aided by a humid environment. The dutch oven traps in the water vapor which keeps the surface of the sourdough moist enough for it to expand. This is also why scoring is important; it allows the bread to open up via that tear. 
    * Using the pizza stone with the bottom of a dutch oven inverted over the stone works really well for me. It makes it easier to dump the dough onto a surface without sides which makes it easier to score.
        - If you don't have a dutch oven, there are plenty of resources for getting enough humidity in the oven to get oven spring!
    * When scoring the dough, you can use your fingers to hold down the side you're starting the slash from. This gives a little more tension.
    * Apparently if you want an ear on your loaf (which you do), then you ought to score the dough with your knife almost parallel to the countertop. 
        * Dull knives are really sad for this. The serrated knife worked better than a dull knife. 
        * You’re supposed to use a [bread lame](https://en.wikipedia.org/wiki/Lame_(kitchen_tool)) (razer on a stick) to score your bread. 
<div><img style="padding: 25px" src="images/sourdough/purple-bread.jpg" width="200" border="50" align="right"/></div>
* You can add other things to your sourdough! I tried adding purple sweet potato. This was awesome & so easy. Add any mixins when you add salt. Other people say after the first fold. Whatever. The potato dissolved into the dough and the resulting loaf was purple, extra sour^[My hypothesis is the sugar in the potato was more yummy to the yeast and it was more active. It certainty rose more!], and sticky spongy. It did not, however, really taste like potato.
* More whole wheat flour = faster fermentation. There's more yummy stuff for the yeast. You don't have to use the same ratio of flour (or even the same types of flour) for your starter as for your bread. Also whole wheat flour soaks up more water than all purpose, so if you use more whole wheat you may also need more water. 
* Is your bread a little flat? Building tension via shaping is the most important thing for helping your dough stand up. That, and don’t overproof your dough (use the finger poke method described below). Check out how to shape dough [here](https://www.youtube.com/watch?v=vEG1BjWroT0) , or [here](https://www.youtube.com/watch?v=ww78_SfGyQE&t=359s), or [here](https://www.youtube.com/watch?v=IxVSlizlt-s).


When we weren't in quarantine, I did things very differently, and it also worked out great & didn't take up too much time: about 1 hr active time start to finish. I can write that up if/when we ever go back to going into the office. 

## Variations: Pizza & Foccacia <a name="variation"></a>
<div><img style="padding: 25px" src="images/sourdough/pizza.jpg" width="200" border="50" align="right"/></div>

Pizza & foccacia is literally the same stuff. For both, I skip the final shape, use a more hydrated dough (83% instead of 73%), and still proof overnight. For foccacia (which is basically over-proofed dough), you're going to want to proof the dough on the sheet pan for a few hours on the counter-top before you bake (remember to oil the sheet pan before you lay the dough on top!). 


## More detailed starter notes <a name="starter"></a>

Keeping starter around is such a chore. Either just keep it in the fridge and feed it the night before you want to use it, or steal it from your neighbor when you want to bake. We've gone a full three weeks without feeding it in the fridge and it's, like, okay. 

Keeping starter around can also be fine. I keep my starter on the counter and feed it every day. It totally owns me and my morning routine. But if you bake more than once a week, then it seems worth it since you'd have to feed it the night before you bake anyways.

*Keep it minimal.* I keep just 30g of starter at any given time on the counter. I also keep a jar in the fridge for discard. Every morning, I:

* Move 20g of starter into the "discard jar" and put it back in the fridge.
* Pour 10g of water into the starter dish, stir it around to dissolve the starter in the water
* Add 10g of flour to the starter dish. 

I bet you could totally keep around even less with the [scrapings method](https://www.youtube.com/watch?v=Uj6YpNCUYYQ&t=324s) if it made a meaningful difference to your flour stash. 

Also, apparently, the temperature you keep your starter at affects the smell & taste. Cooler temp (aka fridge) = more lactic acid = more sour. Warmer temp (aka counter-top) = more acetic acid = less sour, more floral. 

If you're starting a starter from scratch, check out King Arthur Flour's [guide](https://www.kingarthurflour.com/recipes/sourdough-starter-recipe)


## Use your discard <a name="discard"></a>
[NYT  Cooking](https://www.nytimes.com/2020/04/28/dining/sourdough-discard.html) said it best:

> "Sourdough starters are generally a 1:1 ratio of flour to water by weight. Half of the weight is flour, and half of the weight is water. To add discard to any baked good, subtract the flour and water (or liquid) amounts in the discard from the original recipe. For example, if you want to add 115 grams discard to a recipe, remove 57 grams of flour and 57 grams liquid from the amounts the recipe originally called for."

When the "discard jar" gets to like a 1/2 cup or so (I keep mine in a mason jar, so it's easy to see the quantity of it), I go on King Arthur Flour and look up some [discard recipes](https://www.kingarthurflour.com/search?query=discard&algolia-index=recipe_index&hide-tabs=1). Here are some I've liked:

- Crumpets: literally add (to that same jar): 4g sugar, 4g salt, and 2g baking soda to 1 cup starter (260g). Then oil a non-stick pan, and pour it on. When large bubbles form and the pancake sets, flip it over. So simple. So tasty^[Apparently my friend just straight up pours the starter onto the pan and then eats that with maple syrup. She claims to like it. I tried that once, and it was too sour for me. My theory is the baking soda reacts with acidity and it makes the final crumpet less sour. So don't skip it! It also majorly helps with rise. I totally don't have a "crumpet former" but you can use one, it's still delicious and crisp on the bottom.].
    * For variations: add scallions (or green garlic)^[If you know me, you know I looooove garlic, but every week we find only green garlic in our CSA box.] and/or sesame seeds.
- Buttermilk, sourdough pancakes. And instead of buttermilk, we used the leftover whey we had from turning our on-the-way-out milk into cheese. 
- Banana bread: Follow [Joshua Weissman's banana bread](https://www.youtube.com/watch?v=ToBMly0nx4Q).
    * Make this vegan by just leaving out the egg and swap out the butter with canola oil. Here are some ingredient quantities for vegan banana bread: bananas (3), vanilla extract (4g), sugar (14g), brown sugar (50g), canola oil (36g), ap flour (150g), starter (90g), baking soda (1tsp), cinnamon (1tsp), salt (3g), chocolate chips/walnuts/oats (to taste!!). Bake at 350 for 45 min then check if it needs 5 more min.
- Coooooookies! Follow [Joshua Weissman again](https://www.youtube.com/watch?v=wyuec0PPz68).
- Just add it to random stuff. Works great, 10/10, would experiment again. My roommate made lentil pancakes with the sourdough discard that we had just kept in the fridge for a while, and the discard got pretty active and started eating the pancakes, so I'd be aware that it'll keep fermenting if you wait for a while between adding the starter and cooking the dough. If you don't want it to ferment/rise, go ahead and use the dough immediately and the discard just adds a little flavor and saves on some flour. If you want it to ferment/rise, then let it linger for a while! Maybe in your fridge while you forget about it for a few days... oops. 

## HAPPY BAKING
Send me pictures!! I love seeing pictures of crumb!!!! and crust!!!

Thanks for making it to the end! This writeup ended up being far longer than I expected! Hope it was helpful & you got some good pointers to fall deep into bun land with me. 

& thank you to my beautiful roommates who have eaten their way through all my experiments. You both make quarantine a lot of fun and hella tasty!

& thank you to Grandma for reminding me that the oven door is hot, and I should always remember to open it all the way to take something out. 

<div>
  <img style="margin-left:25%; width:50%" src="images/sourdough/suns-out-tongues-out.jpg">
</div>

## More Resources <a name="resources"></a>
* [Foodgeek](https://www.youtube.com/watch?v=Znv99QbfWGs) makes awesome videos answering questions like: "[Can you bake sourdough bread with all-purpose flour?](https://www.youtube.com/watch?v=6UPdNUbk8Qg)," and "[Should you stretch and fold your dough? What is the best way to knead?](https://www.youtube.com/watch?v=Lz9CO1PJ0sM)". Get all your questions answered!!
    * [everyday sourdough](https://www.youtube.com/watch?v=ApANfdFdyz0)
* [Full Proof Baking](https://www.youtube.com/watch?v=HlJEjW-QSnQ): a totally underrated Youtube channel with excellent, to-the-point videos.
* [Joshua Weissman](https://www.youtube.com/watch?v=jJpIzr2sCDE)
* [Jack Bakes](https://www.youtube.com/watch?v=vmb0wWKITBQ)
* [Tim Passmore](https://www.instagram.com/sourdough_tim/?hl=en) on Instagram.